name = "RoactRodux"
author = "Roblox"
license = "Apache-2.0"
content_root = "lib"
version = "0.1.0"

[dependencies]
Roact = { git = "https://github.com/Roblox/Roact", rev = "master" }
Rodux = { git = "https://github.com/Roblox/Rodux", rev = "master" }